language: node_js

node_js:
  - 9.8.0

cache:
  yarn: true
  directories:
  - node_modules

script:
  - yarn lint
  - yarn build
  - yarn test --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
